# Generated by Django 5.2.8 on 2025-11-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='srno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
